const ECHO_REQUEST = 128;
const ECHO_REPLY = 129;
const MLD_LISTENER_QUERY = 130;
const MLD_LISTENER_REPORT = 131;
const ND_ROUTER_SOLICIT = 133;
const ND_ROUTER_ADVERT = 134;
const ND_NEIGHBOR_SOLICIT = 135;
const ND_NEIGHBOR_ADVERT = 136;
const WRU_REQUEST = 139;
const WRU_REPLY = 140;
const HAAD_REQUEST = 144;
const HAAD_REPLY = 145;

const TYPE_MAPPER = new Map();
TYPE_MAPPER.set(ECHO_REQUEST, ECHO_REPLY);
TYPE_MAPPER.set(ECHO_REPLY, ECHO_REQUEST);
TYPE_MAPPER.set(MLD_LISTENER_QUERY, MLD_LISTENER_REPORT);
TYPE_MAPPER.set(MLD_LISTENER_REPORT, MLD_LISTENER_QUERY);
TYPE_MAPPER.set(ND_ROUTER_SOLICIT, ND_ROUTER_ADVERT);
TYPE_MAPPER.set(ND_ROUTER_ADVERT, ND_ROUTER_SOLICIT);
TYPE_MAPPER.set(ND_NEIGHBOR_SOLICIT, ND_NEIGHBOR_ADVERT);
TYPE_MAPPER.set(ND_NEIGHBOR_ADVERT, ND_NEIGHBOR_SOLICIT);
TYPE_MAPPER.set(WRU_REQUEST, WRU_REPLY);
TYPE_MAPPER.set(WRU_REPLY, WRU_REQUEST);
TYPE_MAPPER.set(HAAD_REQUEST, HAAD_REPLY);
TYPE_MAPPER.set(HAAD_REPLY, HAAD_REQUEST);

exports.get_port_equivalents = function(mtype, mcode) {
    if (! TYPE_MAPPER.has(mtype))
        return [mtype, mcode, true];

    return [mtype, TYPE_MAPPER.get(mtype), false];
}
